### ISSUE TITLE
Support for resizing columns

### ISSUE THREAD

**Issue by bggoxp** [nick-keller/react-datasheet-grid#164]
Hi!
Are there any plans to support resizing of columns?

**Comment by faheemhameed** [comment]
This would be great for us as well.

Great work!!!

**Comment by nick-keller** [comment]
Hey, thx for the suggestion, feel free to contribute to the discussion: https://github.com/nick-keller/react-datasheet-grid/discussions/54
(closing this issue as it is redundant)
