### ISSUE TITLE
Double click item to edit

### ISSUE THREAD

**Issue by kechen123** [nick-keller/react-datasheet-grid#167]
Double click item no text is selected, no cursor appears, but can enter it for editing.
The function can be used normally a few days ago🤦‍♂️🤦‍♂️

browser：chrome 103.0.5060.114

Operating system：window11
[video (1).webm](https://user-images.githubusercontent.com/16396880/178400312-bf989182-dcbb-404c-8432-27d3250cd6f8.webm)

**Comment by nick-keller** [comment]
Hey @kechen123, thx for the report.
It works on Chrome Version 103.0.5060.114 on a Mac.
Can you please confirm that it still does not work on Windows?

**Comment by kechen123** [comment]
> 嘿@kechen123，谢谢报告。 它适用于 Mac 上的 Chrome 版本 103.0.5060.114。 您能否确认它仍然无法在 Windows 上运行？

Yes, I tried again just now. The problem still exists
