### ISSUE TITLE
Dynamic cell/row height

### ISSUE THREAD

**Issue by EdvinTr** [nick-keller/react-datasheet-grid#234]
Hi!
I really enjoy using this library but I have run into a problem regarding cell heights. In my current project certain cells may have longer texts within them. These texts are currently being cutoff since the cells have a set width. 

Is it possible to configure react-datasheet-grid to allow rows to have different heights similar to [AG Grid ](https://www.ag-grid.com/archive/23.1.1/javascript-grid-row-height/)?

**Comment by EdvinTr** [comment]
Created a semi working solution using the rowHeight callback on the datasheet where I calculate height depending on the string length of the cell. 
```typescript
<DynamicDataSheetGrid
        rowHeight={({ rowData, rowIndex }) => {
          return getRowHeight({ rowData, rowIndex }); // custom function
        }}
        // ...
    />

**Comment by akshaytanikatech** [comment]
Hey @EdvinTr, can you provide me getRowHeight function, because i tried returning number and object as {top: 60, height: 60} it still gives error saying `top is not defined`
