### ISSUE TITLE
Tests are broken after upgrading library

### ISSUE THREAD

**Issue by Pamwamba** [nick-keller/react-datasheet-grid#241]
Hi, I'm sorry to open a new issue again.
I was in 4.5.0 and I upgraded to the last version to use Internationalization, but I have some issues about tests and about a custom footer I made.

Context : 
I have a page with the grid, and I set 13 initial columns to it.
My test is really simple, i get elements by className 'dsg-cell-header' and expect to have a length of 13.
Everything worked fine before the upgrade, but now, the test fails because it found only a length of 2.

Here is my test : 
```
it('checks columns', () => {
    const { container } = render(ui)); // ui declared earlier
    const headers = container.getElementsByClassName('dsg-cell-header');
    expect(headers).toHaveLength(13);
});
```

The error : 
```
Error: expect(received).toHaveLength(expected)

Expected length: 13
Received length: 2
```

About the custom footer issue : 
Context : I have another page with the grid and a custom footer with selects, that are matching with columns
This is how it looked like before the upgrade : 
![image](https://user-images.githubusercontent.com/25431260/212873684-9a060d36-490c-4b51-bf50-32e2367c3fb1.png)

This is what I got now : 
![image](https://user-images.githubusercontent.com/25431260/212873960-7dddb1a0-92ef-4712-b13b-f5c747829959.png)

All my Selects are overlaying.
**EDIT: fixed it with css but i don't understand why i had to change my css. Tests are still broken.**

Is there something about the structure that changed since 4.5.0 ?
I tried 4.6.0 but I have the same issues

**Comment by faseehahmed1** [comment]
@Pamwamba I've got the same issue after upgrading did you manage to find a fix?

**Comment by Pamwamba** [comment]
Hi, unfortunately no. We stayed in a version that doesn't have this issue,
because we can't spend a lot of time on this.
