### ISSUE TITLE
Paste error in editing mode after version 4.10.x

### ISSUE THREAD

**Issue by devourer3** [nick-keller/react-datasheet-grid#262]
Hi Keller!
Thank you very much for always caring about good libraries.
There is an error that paste does not work during editing mode.
My guess is that it doesn't work because of the event.preventDefault() function.
I've requested a PR before, so I'd like you to check it out and fix it.
I'll upload a video of the previous version 4.9.3 and the current version 4.10.2 for comparison!

4.9.3

https://user-images.githubusercontent.com/30230285/218985356-86c6a3a5-a2ec-44c5-9543-7b80b646983d.mov

4.10.2

https://user-images.githubusercontent.com/30230285/218985520-5c90f4c5-d983-4afa-9afe-f99d1686921d.mov

**Comment by nick-keller** [comment]
Fixed in 4.10.3

**Comment by devourer3** [comment]
it works! thanks!!
