### ISSUE TITLE
Component flickering nonstop NextJS 

### ISSUE THREAD

**Issue by vozmarkov** [nick-keller/react-datasheet-grid#264]
Tried using the[ typescript](https://react-datasheet-grid.netlify.app/docs/typescript) example and the component just flickers on the screen 
see below 
![react-datasheet-grid-flickering-issue](https://user-images.githubusercontent.com/19889621/219874446-59fd7c0c-7548-4c28-b182-57ecff0fd822.gif)

**Issue is not seen on version** 
    "react-datasheet-grid": "^4.5.0",

**Issue is seen on version**   
  4.6.0 and above

**Version used in gif (latest)** 
    "react-datasheet-grid": "^4.10.3",

**Warning seen in terminal output:** 

> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
>     at C:\Dev\eot\node_modules\react-datasheet-grid\dist\columns\checkboxColumn.js:44:51
>     at KeyComponent (C:\Dev\eot\node_modules\react-datasheet-grid\dist\columns\keyColumn.js:40:66)
>     at div
>     at Cell (C:\Dev\eot\node_modules\react-datasheet-grid\dist\components\Cell.js:9:17)
>     at div
>     at div
>     at div
>     at Grid (C:\Dev\eot\node_modules\react-datasheet-grid\dist\components\Grid.js:35:17)
>     at div
>     at C:\Dev\eot\node_modules\react-datasheet-grid\dist\components\DataSheetGrid.js:63:83
>     at C:\Dev\eot\node_modules\react-datasheet-grid\dist\components\StaticDataSheetGrid.js:22:11
>     at DataGrid (webpack-internal:///./src/features/dashboard/DataGrid.tsx:19:76)
>     at Home
>     at main
>     at div
>     at Layout (webpack-internal:///./src/components/layout/Layout.tsx:21:19)
>     at SessionProvider (C:\Dev\eot\node_modules\next-auth\react\index.js:453:24)
>     at MyApp (webpack-internal:///./src/pages/_app.tsx:19:18)
>     at Hydrate (file:///C:/Dev/eot/node_modules/@tanstack/react-query/build/lib/Hydrate.mjs:22:3)
>     at QueryClientProvider (file:///C:/Dev/eot/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:40:3)
>     at TRPCProvider (file:///C:/Dev/eot/node_modules/@trpc/react-query/dist/createHooksInternal-de11647d.mjs:172:17)
>     at WithTRPC (webpack-internal:///./node_modules/@trpc/next/dist/index.mjs:47:83)
>     at StyleRegistry (C:\Dev\eot\node_modules\styled-jsx\dist\index\index.js:449:36)
>     at PathnameContextProviderAdapter (C:\Dev\eot\node_modules\next\dist\shared\lib\router\adapters.js:60:11)
>     at AppContainer (C:\Dev\eot\node_modules\next\dist\server\render.js:290:29)
>     at AppContainerWithIsomorphicFiberStructure (C:\Dev\eot\node_modules\next\dist\server\render.js:326:57)
>     at div
>     at Body (C:\Dev\eot\node_modules\next\dist\server\render.js:613:21)

**Code used:** 
```
import { useState } from "react";
import type { Column } from "react-datasheet-grid";
import {
  checkboxColumn,
  DataSheetGrid,
  keyColumn,
  textColumn,
} from "react-datasheet-grid";
import "react-datasheet-grid/dist/style.css";

// Define your row type anywhere
type Row = {
  active: boolean;
  firstName: string | null;
  lastName: string | null;
};

function DataGrid() {
  // Type your data (not DSG specific)
  const [data, setData] = useState<Row[]>([
    { active: true, firstName: "Elon", lastName: "Musk" },
    { active: false, firstName: "Jeff", lastName: "Bezos" },
  ]);

  // Type your columns to get type checks in your IDE
  const columns: Column<Row>[] = [
    {
      ...keyColumn<Row, "active">("active", checkboxColumn),
      title: "Active",
    },
    {
      ...keyColumn<Row, "firstName">("firstName", textColumn),
      title: "First name",
    },
    {
      ...keyColumn<Row, "lastName">("lastName", textColumn),
      title: "Last name",
    },
  ];

  return <DataSheetGrid value={data} onChange={setData} columns={columns} />;
}

export default DataGrid;
```

Project build using [T3 stack ](https://create.t3.gg/)

**Package.json file**
```
{
  "name": "eot",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "next build",
    "dev": "next dev",
    "postinstall": "prisma generate",
    "lint": "next lint",
    "start": "next start"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.7",
    "@heroicons/react": "^2.0.13",
    "@next-auth/prisma-adapter": "^1.0.5",
    "@prisma/client": "^4.9.0",
    "@tanstack/react-query": "^4.16.0",
    "@tanstack/react-table": "^8.7.9",
    "@trpc/client": "^10.0.0",
    "@trpc/next": "^10.0.0",
    "@trpc/react-query": "^10.0.0",
    "@trpc/server": "^10.0.0",
    "@types/react-text-truncate": "^0.14.1",
    "next": "13.1.1",
    "next-auth": "^4.18.3",
    "react": "18.2.0",
    "react-datasheet-grid": "^4.10.3",
    "react-datasheet-grid-nextjs": "^4.4.9",
    "react-dom": "18.2.0",
    "react-text-truncate": "^0.19.0",
    "superjson": "1.9.1",
    "zod": "^3.18.0"
  },
  "devDependencies": {
    "@types/node": "^18.0.0",
    "@types/prettier": "^2.7.2",
    "@types/react": "^18.0.14",
    "@types/react-dom": "^18.0.5",
    "@typescript-eslint/eslint-plugin": "^5.33.0",
    "@typescript-eslint/parser": "^5.33.0",
    "autoprefixer": "^10.4.7",
    "eslint": "^8.26.0",
    "eslint-config-next": "13.1.1",
    "postcss": "^8.4.14",
    "prettier": "^2.8.1",
    "prettier-plugin-tailwindcss": "^0.2.1",
    "prisma": "^4.9.0",
    "tailwindcss": "^3.2.0",
    "typescript": "^4.8.4"
  },
  "ct3aMetadata": {
    "initVersion": "6.11.5"
  }
}

```

**Comment by vozmarkov** [comment]
Defining fully all the column tables that are needed for my sheet stopped the flickering.

**Comment by jeffhennis** [comment]
> Defining fully all the column tables that are needed for my sheet stopped the flickering.

@vozmarkov what exactly did you do? I am experiencing the exact same issue.

**Comment by gyoridavid** [comment]
> > Defining fully all the column tables that are needed for my sheet stopped the flickering.
> 
> @vozmarkov what exactly did you do? I am experiencing the exact same issue.

For my case, the `flex: 1` was causing the layout recalculation loop, and the `w-full overflow:hidden` didn't solve the problem.
The solution was to wrap the component with the following div:

**Comment by vozmarkov** [comment]
> > > Defining fully all the column tables that are needed for my sheet stopped the flickering.
> > 
> > @vozmarkov what exactly did you do? I am experiencing the exact same issue.
> 
> For my case, the `flex: 1` was causing the layout recalculation loop, and the `w-full overflow:hidden` didn't solve the problem.
> The solution was to wrap the component with the following div:
> 
> ```
> <div className="grid grid-cols-[minmax(0,1fr)] overflow-hidden">
>   <DataSheetGrid...
> </div>

I haven't been in that part of the code for long time but here is a snippet of my code.
It looks like I used dynamic grid with parent div set to h-80vh 

      {isLoading && <Spinner containerClass="h-[80vh]" />}
      <div className="h-[80vh]">
        {!isLoading && (
          <DynamicDataSheetGrid
            height={height && height - 200}
            value={data}
            columns={columns}
            headerRowHeight={50}
            rowHeight={50}
