### ISSUE TITLE
When inputting with Cell selected, the first letter is fixed in English.

### ISSUE THREAD

**Issue by yoe88** [nick-keller/react-datasheet-grid#306]
Hello nick-keller!
I am Korean.
When entering Korean with Cell selected, the first letter is entered in English.
There is no problem when it is focused.

For example, on a Korean keyboard, key "a" is the same as key "ㅁ".
If you type "ㅁㅁㅁ", the first letter is changed to "aㅁㅁ".
Could you please correct this?

**Comment by chachagogogo** [comment]
Is it solved???
